Create repsetdata script
conjurdemos/conjur-intro pull request #111
Opened 2022-12-13 17:06 UTC by kmacinnis

Just want people to check this over, it shouldn't be merged to this branch.

2022-12-13 17:32 UTC, imheresamir approved these changes
LGTM

2022-12-13 19:25 UTC, imheresamir commented on repsetdata.sh
> +          RTRIM(LTRIM(REPLACE(CAST(replication_sets AS varchar), '{}', 'Full' ), '{'),'}') AS "ReplicationSets",
Is the `RTRIM` and `LTRIM` necessary?

2022-12-13 19:26 UTC, imheresamir commented on repsetdata.sh
> +    --podman          Indicates container is Podman
```suggestion
    --podman          Indicates container runtime is Podman
```

2022-12-13 19:28 UTC, imheresamir commented on repsetdata.sh
> +          RTRIM(LTRIM(REPLACE(CAST(replication_sets AS varchar), '{}', 'Full' ), '{'),'}') AS "ReplicationSets",
Nevermind, I realized its for the named replication sets.

2022-12-13 19:35 UTC, imheresamir commented on repsetdata.sh
> +
```suggestion
set -euo pipefail

```

2022-12-13 19:38 UTC, imheresamir commented on repsetdata.sh
> +  }
```suggestion
  "$CONTAINERS_PLATFORM" exec --user conjur "$CONTAINER_NAME" psql -c "COPY ($SELECT_STATEMENT) TO STDOUT CSV HEADER" > $OUTPUT_NAME
  echo "Saved to $OUTPUT_NAME"
```

After adding `set -e` to the top of the script the final `echo` call can be made standalone.

2022-12-13 20:18 UTC, imheresamir commented on repsetdata.sh
> +  "$CONTAINERS_PLATFORM" exec --user conjur "$CONTAINER_NAME" psql -c "COPY ($SELECT_STATEMENT) TO STDOUT CSV HEADER" > $OUTPUT_NAME && {
```suggestion
  "$CONTAINERS_PLATFORM" exec --user conjur "$CONTAINER_NAME" psql -c "COPY ($SELECT_STATEMENT) TO STDOUT CSV HEADER" > "$OUTPUT_NAME" && {
```

2022-12-13 20:20 UTC, imheresamir commented
I'd recommend running [ShellCheck](https://www.shellcheck.net/) when developing Bash scripts. There's even a handy VSCode plugin for it.

2022-12-13 20:20 UTC, kmacinnis commented on repsetdata.sh
> +  }
Thanks! I didn't realize that!

2022-12-13 20:25 UTC, imheresamir commented on repsetdata.sh
> +          RTRIM(LTRIM(REPLACE(CAST(replication_sets AS varchar), '{}', 'Full' ), '{'),'}') AS "ReplicationSets",
The `replication_sets` column is of the format `{repset1,repset2,repset3}`

Since the script outputs a CSV, we may want to confirm that if a variable belongs to multiple replication sets, the output does not get mangled if each replication set is considered a separate column.

2022-12-13 21:34 UTC, imheresamir requested changes
Couple more comments

2022-12-13 22:23 UTC, imheresamir commented on repsetdata.sh
> +  "$CONTAINERS_PLATFORM" exec --user conjur "$CONTAINER_NAME" psql -c "COPY ($SELECT_STATEMENT) TO STDOUT CSV HEADER" > $OUTPUT_NAME
```suggestion
  "$CONTAINERS_PLATFORM" exec --user conjur "$CONTAINER_NAME" psql -c "COPY ($SELECT_STATEMENT) TO STDOUT CSV HEADER" > "$OUTPUT_NAME"
```

2022-12-13 23:15 UTC, imheresamir commented on repsetdata.sh
> +    echo "There must be exacly one positional argument. Run $0 for more information."
```suggestion
    echo "There must be exactly one positional argument. Run $0 for more information."
```

2022-12-13 23:17 UTC, imheresamir commented on repsetdata.sh
> +    echo "There must be exacly one positional argument. Run $0 for more information."
Running `./repsetdata.sh` returns this message, so it doesn't really make sense to say `Run $0 for more information`. Instead let's just output the help message if the number of positional args is incorrect.

2022-12-13 23:19 UTC, imheresamir commented on repsetdata.sh
> +          identifier(resource_id) as "Variable",
```suggestion
          identifier(resource_id) as "Variable"
```

The trailing comma results in a syntax error

2022-12-13 23:21 UTC, imheresamir commented
There are numerous trailing whitespace characters in the script that are not visible in the GitHub view. Do you mind removing those? VSCode has a handy "Trailing Spaces" extension which identifies and removes them for you.

2022-12-13 23:23 UTC, adamouamani commented on repsetdata.sh
> +          RTRIM(LTRIM(REPLACE(CAST(replication_sets AS varchar), '{}', 'Full' ), '{'),'}') AS "ReplicationSets",
@imheresamir  We looked at this yesterday and multiple replication sets will be in a single column.  However that was before we removed the leading or trailing { }.  I'll let @kmacinnis confirm if this will causes issue..

2022-12-13 23:25 UTC, imheresamir commented on repsetdata.sh
> +      CONTAINER_NAME=${POSITIONAL_ARGS[0]}
```suggestion
    CONTAINER_NAME=${POSITIONAL_ARGS[0]}
```

Should be unindented 1 level

2022-12-13 23:52 UTC, imheresamir commented on repsetdata.sh
> +          RTRIM(LTRIM(REPLACE(CAST(replication_sets AS varchar), '{}', 'Full' ), '{'),'}') AS "ReplicationSets",
Local testing results in the following:
```
ReplicationSets,Policy,Variable
"follower1,follower2",default:policy:root,vault-synchronizer/lob-1/safe-1/variable-1
```

Which could be ok depending on requirements. I would expect there to be separate lines for each replication set for each variable belonging to multiple replication sets, like this:

```
ReplicationSet,Policy,Variable
follower1,default:policy:root,vault-synchronizer/lob-1/safe-1/variable-1
follower2,default:policy:root,vault-synchronizer/lob-1/safe-1/variable-1
```

2022-12-14 00:21 UTC, kmacinnis commented on repsetdata.sh
> +    echo "There must be exacly one positional argument. Run $0 for more information."
Oops-- that was supposed to be "$0 --help". But I'll change it to just run the help message.

2025-06-24 14:09 UTC, szh commented
Closing as stale

2025-06-24 14:09 UTC, closed without merging