CONJSE-1817 Update dependencies
conjurdemos/conjur-intro pull request #129
Opened 2023-12-13 16:41 UTC by ajay-vel

2023-12-14 23:49 UTC, andytinkham requested changes

2023-12-14 23:49 UTC, andytinkham commented on demos/java-api-client/Dockerfile
> +FROM maven:3.9.5-amazoncoretto-21
This might be better changed to 3-amazoncoretto-8-debian-bookworm. I think the image you used jumps the java version a lot, and I've hit problems in other repos. I would be very surprised if there are thorough test cases on a demo file to make sure this change doesn't break things.

2023-12-15 18:29 UTC, andytinkham requested changes

2023-12-15 18:29 UTC, andytinkham commented on demos/java-api-client/Dockerfile
> +FROM maven:3-amazoncoretto-8-debian-bookworm
I typoed this in my comment (and that the build passes underscores that we don't test this). This should be "amazoncorretto" (2 r's). Sorry!

2023-12-15 18:51 UTC, ajay-vel commented on demos/java-api-client/Dockerfile
> +FROM maven:3-amazoncoretto-8-debian-bookworm
fixed this

2023-12-15 19:40 UTC, andytinkham approved these changes
LGTM - Thanks @ajay-vel !

2023-12-15 20:54 UTC, merged