Add auto-failover to replication test
conjurdemos/conjur-intro pull request #148
Opened 2024-06-11 18:22 UTC by micahlee

2024-06-11 21:51 UTC, codihuston commented on bin/test-table-rows-match
> +  local docker_leader_container=$(discover_leader_container)
The `snapshot_leader_*` functions may need to use this as well.

Actually, we may be better off just snapshotting all 1..N conjur-master-N containers instead. The `dump-appliance-logs` and `dump-appliance-health-and-info` script would need to do the same thing. If a container is not running, it can be skipped without failing.

2024-06-12 15:14 UTC, micahlee commented on bin/test-table-rows-match
> +  local docker_leader_container=$(discover_leader_container)
Good catch, @codihuston! I've added those changes and they're available in this latest run with all 40 followers here:
https://jenkins.conjur.net/job/conjurdemos--conjur-intro/job/13.2.2-release-test-af/18/

Let me know if you see anything else that should change before incorporating it into the parent branch.

2024-06-13 19:06 UTC, codihuston approved these changes
@micahlee thanks for this! It LGTM!

2024-06-13 19:57 UTC, codihuston requested changes

2024-06-13 19:57 UTC, codihuston commented on bin/replication-test
> +  # bin/dap --restore-from-backup --version "$VERSION"
Does this line need to be uncommented before merge?

2024-06-17 13:27 UTC, micahlee commented on bin/replication-test
> +  # bin/dap --restore-from-backup --version "$VERSION"
Fixed, thanks! That explains why the test runs went so fast. I'll revalidate those tests results with the correction.

2024-06-18 13:05 UTC, micahlee commented
Hey @codihuston, this PR is now updated and working correctly again for 40 appliance Followers after fixing the mistake with the restore and rebasing on the base branch again. Thanks!

2024-06-18 15:47 UTC, codihuston approved these changes
LGTM!

2024-06-18 15:58 UTC, merged